### ISSUE TITLE
MariaDb Columnstore not found in docker hub

### ISSUE THREAD

**Issue by pantonis** [mariadb-corporation/mariadb-columnstore-docker#24]
Im trying to install MariaDb Column store using docker from dockerhub but there is no such image. How can I use it using docker? Where can I find the image?

**Comment by toddstoffel** [comment]
The Docker Hub repository is currently in private mode, however the image can be built using the instructions in the README here on GitHub.

**Comment by rumsrami** [comment]
Can you please clarify, what is the licence on this repo?

**Comment by pantonis** [comment]
@toddstoffel any plans to make it public again in the future or this is a permanent decision?

**Comment by flopana** [comment]
@pantonis Two months ago they pushed a breaking change which messed up the database completely and rendered it unusable. It took them two weeks for an RTFM to a newly changed documentation. When I first used this image you didn't need to set up a cluster you could just choose the columnstore engine like any other.

In the meantime I had to use an old image I luckily still had flying around because they delete old versions from dockerhub immediately after releasing a new one.

Don't expect warnings for important changes like making the repository private. I just came back from vacation just to see that this repo has messed it up again.

https://github.com/mariadb-corporation/mariadb-columnstore-docker/issues/20 this is the issue I was talking about

**Comment by pvannierop** [comment]
@toddstoffel 
> The Docker Hub repository is currently in private mode, however the image can be built using the instructions in the README here on GitHub.

This build step requires a token and the build script states that this is for ColumnStore devs only. Could you elaborate on how to build the CS docker image?

**Comment by toddstoffel** [comment]
Disregard the Dev section, that's for internal testing. You can find your token here: https://customers.mariadb.com/downloads/token/

**Comment by toddstoffel** [comment]
We plan to move required components (CMAPI, etc) in this project to a completely open source model soon.  At that time, I will update this project to use the community version and the Docker image will again be available from Docker Hub.

**Comment by pvannierop** [comment]
@toddstoffel A token is not available to _community_ users (which I am at the moment). So, does this now completely block me from trying columnstore? That does not appear to be a sound business decision. How can I convince my company to base a product on MariaDB server + columnstore?
