### ISSUE TITLE
Error during image build process

### ISSUE THREAD

**Issue by schrockn** [mariadb-corporation/mariadb-columnstore-docker#3]
Hello! I'd like to try out column store using your image on Docker for Mac.

I used the following build command at the root of the repository: `docker build . -t mariadb-columnstore-image`

Unfortunately during step 4 I get the following error:

Step 4/12 : RUN export USER=root && yum localinstall -y /install/mariadb-columnstore*.rpm && sh /install/install.sh && rm -f /install/*.rpm /install/install.sh
 ---> Running in b022c34abfd4
Loaded plugins: fastestmirror, ovl
Cannot open: /install/mariadb-columnstore*.rpm. Skipping.
Nothing to do
/install/install.sh: line 13: /usr/local/mariadb/columnstore/bin/postConfigure: No such file or directory
/install/install.sh: line 16: /usr/local/mariadb/columnstore/mysql/bin/mysql: No such file or directory
/install/install.sh: line 19: /usr/local/mariadb/columnstore/bin/mcsadmin: No such file or directory
/install/install.sh: line 22: /usr/local/mariadb/columnstore/bin/mcsadmin: No such file or directory

**Comment by davidwbt** [comment]
You need to download the centos 7 rpm install tar.gz file to the same
directory with the reference dockerfile.

**Comment by schrockn** [comment]
I see. 

Is there a recommended way to do this on a mac given that I don't have yum? The repository configuration tool requires it. (see https://downloads.mariadb.org/mariadb/repositories) 

There is also this index of files http://mariadb.mirror.globo.tech/mariadb-10.2.6/yum/centos/ but it's not totally clear to me what files are exactly expected in the tar file since the files are stored in uncompressed and -archived form.

Thanks!

**Comment by davidwbt** [comment]
Just download the file from:

https://mariadb.com/downloads/columnstore



alternatively you could modify the docker file to do this for you and
download directly from:
https://downloads.mariadb.com/ColumnStore/1.0.9/centos/x86_64/7/mariadb-columnstore-1.0.9-1-centos7.x86_64.rpm.tar.gz



but you’d need to update this for each release.





*From:* schrockn [mailto:notifications@github.com]
*Sent:* Wednesday, May 31, 2017 6:26 AM
*To:* mariadb-corporation/mariadb-columnstore-docker <
mariadb-columnstore-docker@noreply.github.com>
*Cc:* davidwbt <dthompson@mariadb.com>; Comment <comment@noreply.github.com>
*Subject:* Re: [mariadb-corporation/mariadb-columnstore-docker] Error
during image build process (#3)



I see.

Is there a recommended way to do this on a mac given that I don't have yum?
The repository configuration tool requires it. (see
https://downloads.mariadb.org/mariadb/repositories)

There is also this index of files
http://mariadb.mirror.globo.tech/mariadb-10.2.6/yum/centos/ but it's not
totally clear to me what files are exactly expected in the tar file since
the files are stored in uncompressed and -archived form.

Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mariadb-corporation/mariadb-columnstore-docker/issues/3#issuecomment-305185735>,
or mute the thread

**Comment by schrockn** [comment]
Great thank you
